--[[if getActivatedMods():contains("ItemTweakerAPI") then
	require("ItemTweaker_Core");
	else return end
	
	TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_Holosight TLOG_HolographicVanilaAR reddottlog reddottlog");
    TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_RedDot TLOG_RedDotVanilaAR reddottlog reddottlog");
    TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_RedDot2 TLOG_RedDot2VanilaAR reddottlog reddottlog");
    TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_x8Scope TLOG_x8ScopeVanilaAR reddottlog reddottlog");
    TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_x4Scope TLOG_x4ScopeVanilaAR reddottlog reddottlog");
    TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_x2Scope TLOG_x2ScopeVanilaAR reddottlog reddottlog");
    TweakItem("Base.AssaultRifle","ModelWeaponPart", "TLOG_VariableScope TLOG_VariableScopeVanilaAR reddottlog reddottlog");
    

    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_Holosight TLOG_HolographicVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_RedDot TLOG_RedDotVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_RedDot2 TLOG_RedDot2VanilaAR2 reddottlog reddottlog");
    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_x8Scope TLOG_x8ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_x4Scope TLOG_x4ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_x2Scope TLOG_x2ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.AssaultRifle2","ModelWeaponPart", "TLOG_VariableScope TLOG_VariableScopeVanilaAR2 reddottlog reddottlog");
    

    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_Holosight TLOG_HolographicVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_RedDot TLOG_RedDotVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_RedDot2 TLOG_RedDot2VanilaAR2 reddottlog reddottlog");
    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_x8Scope TLOG_x8ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_x4Scope TLOG_x4ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_x2Scope TLOG_x2ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.HuntingRifle","ModelWeaponPart", "TLOG_VariableScope TLOG_VariableScopeVanilaAR2 reddottlog reddottlog");
    

    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_Holosight TLOG_HolographicVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_RedDot TLOG_RedDotVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_RedDot2 TLOG_RedDot2VanilaAR2 reddottlog reddottlog");
    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_x8Scope TLOG_x8ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_x4Scope TLOG_x4ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_x2Scope TLOG_x2ScopeVanilaAR2 reddottlog reddottlog");
    TweakItem("Base.VarmintRifle","ModelWeaponPart", "TLOG_VariableScope TLOG_VariableScopeVanilaAR2 reddottlog reddottlog");
    ]]