local rifle = ScriptManager.instance:getItem("AssaultRifle")
    if rifle then
        rifle:DoParam("TorchCone	=	TRUE")
        rifle:DoParam("LightStrength	=	0")
        rifle:DoParam("LightDistance	=	13")
    end
 local rifle2 = ScriptManager.instance:getItem("AssaultRifle2")
    if rifle2 then
        rifle2:DoParam("TorchCone	=	TRUE")
        rifle2:DoParam("LightStrength	=	0")
        rifle2:DoParam("LightDistance	=	13")
    end
    local rifle3 = ScriptManager.instance:getItem("HuntingRifle")
    if rifle3 then
        rifle3:DoParam("TorchCone	=	TRUE")
        rifle3:DoParam("LightStrength	=	0")
        rifle3:DoParam("LightDistance	=	13")
    end
    local rifle4 = ScriptManager.instance:getItem("VarmintRifle")
    if rifle4 then
        rifle4:DoParam("TorchCone	=	TRUE")
        rifle4:DoParam("LightStrength	=	0")
        rifle4:DoParam("LightDistance	=	13")
    end
    local pistol1 = ScriptManager.instance:getItem("Pistol")
    if pistol1 then
        pistol1:DoParam("TorchCone	=	TRUE")
        pistol1:DoParam("LightStrength	=	0")
        pistol1:DoParam("LightDistance	=	10")
    end
    local pistol2 = ScriptManager.instance:getItem("Pistol2")
    if pistol2 then
        pistol2:DoParam("TorchCone	=	TRUE")
        pistol2:DoParam("LightStrength	=	0")
        pistol2:DoParam("LightDistance	=	10")
    end
    local pistol3 = ScriptManager.instance:getItem("Pistol3")
    if pistol3 then
        pistol3:DoParam("TorchCone	=	TRUE")
        pistol3:DoParam("LightStrength	=	0")
        pistol3:DoParam("LightDistance	=	10")
    end
    local shotgun1 = ScriptManager.instance:getItem("Shotgun")
    if shotgun1 then
        shotgun1:DoParam("TorchCone	=	TRUE")
        shotgun1:DoParam("LightStrength	=	0")
        shotgun1:DoParam("LightDistance	=	13")
    end
  local revolver1 = ScriptManager.instance:getItem("Revolver")
    if revolver1 then
        revolver1:DoParam("TorchCone	=	TRUE")
        revolver1:DoParam("LightStrength	=	0")
        revolver1:DoParam("LightDistance	=	10")
    end
    local revolver2 = ScriptManager.instance:getItem("Revolver_Short")
    if revolver2 then
        revolver2:DoParam("TorchCone	=	TRUE")
        revolver2:DoParam("LightStrength	=	0")
        revolver2:DoParam("LightDistance	=	10")
    end
    local revolver3 = ScriptManager.instance:getItem("Revolver_Long")
    if revolver3 then
        revolver3:DoParam("TorchCone	=	TRUE")
        revolver3:DoParam("LightStrength	=	0")
        revolver3:DoParam("LightDistance	=	10")
    end
